// Code generated by protoc-gen-go. DO NOT EDIT.
// source: my-application/pkg/pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TODO: Structure your own protobuf messages. Each protocol buffer message is a
// small logical record of information, containing a series of name-value pairs.
type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_efb451c0b8612192, []int{0}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "service.VersionResponse")
}

func init() {
	proto.RegisterFile("my-application/pkg/pb/service.proto", fileDescriptor_efb451c0b8612192)
}

var fileDescriptor_efb451c0b8612192 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x59, 0x0f, 0xae, 0x06, 0x44, 0xe9, 0x41, 0x4a, 0xf5, 0x20, 0xeb, 0x45, 0xd0, 0x26,
	0xa0, 0x37, 0x3d, 0xad, 0x20, 0x9e, 0x04, 0xd9, 0x83, 0x07, 0x6f, 0x49, 0x9d, 0x8d, 0xc1, 0x36,
	0x33, 0x24, 0xd9, 0xba, 0xbd, 0xfa, 0x0a, 0x3e, 0x9a, 0xaf, 0xe0, 0x83, 0xc8, 0xb6, 0xa9, 0x16,
	0x77, 0x6f, 0xfd, 0x67, 0xa6, 0xdf, 0x07, 0x7f, 0xd8, 0x69, 0xd5, 0xe4, 0x92, 0xa8, 0x34, 0x85,
	0x0c, 0x06, 0xad, 0xa0, 0x37, 0x2d, 0x48, 0x09, 0x0f, 0xae, 0x36, 0x05, 0x70, 0x72, 0x18, 0x30,
	0x19, 0xc7, 0x98, 0x1d, 0x69, 0x44, 0x5d, 0x82, 0x68, 0xc7, 0x6a, 0x31, 0x17, 0x50, 0x51, 0x68,
	0xba, 0xab, 0xec, 0x38, 0x2e, 0x25, 0x19, 0x21, 0xad, 0xc5, 0xd0, 0x12, 0x7d, 0xdc, 0x4e, 0xb5,
	0x09, 0xaf, 0x0b, 0xc5, 0x0b, 0xac, 0x04, 0xd8, 0x1a, 0x1b, 0x72, 0xb8, 0x6c, 0x3a, 0x52, 0x91,
	0x6b, 0xb0, 0x79, 0x2d, 0x4b, 0xf3, 0x22, 0x03, 0x88, 0xb5, 0x8f, 0x88, 0xb8, 0x18, 0x1c, 0xfb,
	0x77, 0xa9, 0x35, 0x38, 0x81, 0xd4, 0x4a, 0x36, 0x08, 0xaf, 0x07, 0x42, 0x63, 0xe7, 0xa8, 0x4a,
	0x5c, 0x22, 0x81, 0x1d, 0x2a, 0x35, 0xba, 0xea, 0x17, 0xb1, 0x0a, 0xdd, 0xbf, 0x93, 0x73, 0xb6,
	0xff, 0x04, 0xce, 0x1b, 0xb4, 0x33, 0xf0, 0x84, 0xd6, 0x43, 0x92, 0xb2, 0x71, 0xdd, 0x8d, 0xd2,
	0xd1, 0xc9, 0xe8, 0x6c, 0x77, 0xd6, 0xc7, 0x4b, 0xc9, 0xf6, 0x1e, 0x9a, 0xe9, 0x5f, 0x87, 0xc9,
	0x23, 0x63, 0xf7, 0x10, 0x22, 0x20, 0x39, 0xe4, 0x5d, 0x2f, 0xbc, 0x2f, 0x8d, 0xdf, 0xad, 0x4a,
	0xcb, 0x52, 0xde, 0x97, 0xfc, 0x4f, 0x35, 0x39, 0xf8, 0xf8, 0xfa, 0xfe, 0xdc, 0x62, 0xc9, 0x8e,
	0x88, 0x8a, 0xdb, 0xec, 0x39, 0xdd, 0xf8, 0x4e, 0x37, 0xa4, 0xd4, 0x76, 0xcb, 0xbd, 0xfa, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x9a, 0x3f, 0x5e, 0xa7, 0xca, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MyApplicationClient is the client API for MyApplication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MyApplicationClient interface {
	GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type myApplicationClient struct {
	cc *grpc.ClientConn
}

func NewMyApplicationClient(cc *grpc.ClientConn) MyApplicationClient {
	return &myApplicationClient{cc}
}

func (c *myApplicationClient) GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/service.MyApplication/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyApplicationServer is the server API for MyApplication service.
type MyApplicationServer interface {
	GetVersion(context.Context, *empty.Empty) (*VersionResponse, error)
}

func RegisterMyApplicationServer(s *grpc.Server, srv MyApplicationServer) {
	s.RegisterService(&_MyApplication_serviceDesc, srv)
}

func _MyApplication_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyApplicationServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.MyApplication/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyApplicationServer).GetVersion(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyApplication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.MyApplication",
	HandlerType: (*MyApplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _MyApplication_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "my-application/pkg/pb/service.proto",
}
